version: '3.3'
services:
  postgres:
    image: postgres:11
    restart: always
    container_name: expert_octo_engine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: expert_octo_engine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    command: postgres -N 100